---
# tasks file for nodejs
- name: create build directory
  file:
    path: "{{ container_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: copy files to the nodejs node
  copy:
    src: nodejs/
    dest: "{{ container_path }}"

- name: remove {{ container_name }} container and {{ image_name }} if exists
  shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"

- name: build container image
  docker_image:
    name: "{{ image_name }}"
    build:
      path: "{{ container_path }}"
    source: build
    state: present
  notify: Launch nodejs docker container
